FROM golang:1.25.1 AS build
WORKDIR /app
COPY . .
RUN go build -o gateway ./cmd/gateway


FROM debian:stable-slim
WORKDIR /app
COPY --from=build /app/gateway .
COPY certs/ /certs/
EXPOSE 8443
CMD ["./gateway"]
