# Stage 1: Build
FROM golang:1.25.1 AS build
WORKDIR /app
COPY . .
RUN go build -o echo main.go

# Stage 2: Minimal runtime
FROM debian:stable-slim
WORKDIR /app
COPY --from=build /app/echo .
EXPOSE 8081
CMD ["./echo"]
